deployment:
  tasks:
    - export DEPLOYPATH=/home/ckejobqv/zing_healthy_eats/
    - /bin/cp -r app $DEPLOYPATH
    - /bin/cp -r static $DEPLOYPATH
    - /bin/cp -r templates $DEPLOYPATH
    - /bin/cp config.py $DEPLOYPATH
    - /bin/cp passenger_wsgi.py $DEPLOYPATH
    - /bin/cp requirements.txt $DEPLOYPATH
    - /bin/cp run.py $DEPLOYPATH
